# Generated by Django 4.1.1 on 2022-09-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='audio',
            field=models.FileField(max_length=250, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.FileField(max_length=255, null=True, upload_to='video/'),
        ),
    ]
