# Generated by Django 4.1.1 on 2022-10-03 08:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_alter_content_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='speciality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=list, null=True, size=None),
        ),
    ]
