# Generated by Django 4.1.1 on 2022-10-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_alter_content_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='speciality',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
