# Generated by Django 4.1.1 on 2022-10-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0005_content_html_content_content_short_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='meeting_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='audio_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='text_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='video_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
