# Generated by Django 4.1.1 on 2022-10-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0006_content_meeting_link_language_audio_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='home_native',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
