# Generated by Django 4.1.1 on 2022-11-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0007_language_home_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='short_video_thumbnail_desktop',
            field=models.ImageField(null=True, upload_to='content/short_video/desktop'),
        ),
        migrations.AddField(
            model_name='content',
            name='short_video_thumbnail_mobile',
            field=models.ImageField(null=True, upload_to='content/short_video/mobile'),
        ),
        migrations.AddField(
            model_name='content',
            name='video_thumbnail_desktop',
            field=models.ImageField(null=True, upload_to='content/video/desktop'),
        ),
        migrations.AddField(
            model_name='content',
            name='video_thumbnail_mobile',
            field=models.ImageField(null=True, upload_to='content/video/mobile'),
        ),
        migrations.AddField(
            model_name='language',
            name='meeting_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='reviews_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
