# Generated by Django 4.1.1 on 2022-11-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0008_content_short_video_thumbnail_desktop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='home_native',
            new_name='home_name',
        ),
    ]
